# Configuración básica para sonar-project.properties
sonar.projectKey=tienda-ropa
sonar.projectName=Tienda Ropa
sonar.projectVersion=1.0

# Directorios de código fuente
sonar.sources=.

# Excluir directorios de dependencias, si los tienes
sonar.exclusions=**/vendor/**

# Directorios de pruebas (si existen)
sonar.tests=tests

# Tipo de lenguaje
sonar.language=php
